os:
- linux
language: node_js
notifications:
  email:
    on_success: never
    on_failure: never
sudo: true
branches:
  only:
  - master
  - develop
node_js:
- '7'
- '6'
- '4'
cache:
  apt: true
  directories:
  - node_modules
before_install: npm install -g grunt-cli
script: npm run-script test-travis
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js